mui.init();
mui("body").on("tap",".index",function(){
	mui.openWindow({
		url:'index.html'
	});
})
mui("body").on("tap",".Notice",function(){
	mui.openWindow({
		url:'Notice.html'
	});
})
mui("body").on("tap",".center",function(){
	mui.openWindow({
		url:'center.html'
	});
})
mui("body").on("tap",".cus",function(){
	mui.openWindow({
		url:'http://p.qiao.baidu.com/cps/chat?siteId=12618572&userId=1525167'
	});
})
